# Generated by Django 6.0.3 on 2026-04-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishi', '0003_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='coordinates',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
