# Generated by Django 6.0.3 on 2026-04-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishi', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Sold', 'Sold'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
    ]
