# Generated by Django 6.0.3 on 2026-04-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishi', '0007_order_payment_status_order_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('upi', 'UPI'), ('debit', 'Debit Card'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
