# Generated by Django 6.0.3 on 2026-04-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishi', '0008_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
