# Generated by Django 6.0.3 on 2026-04-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishi', '0010_useraccount_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='screenshot_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Pending Verification', 'Pending Verification'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Sold', 'Sold'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
    ]
