# Generated by Django 6.0.3 on 2026-04-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishi', '0015_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='wishlist',
            field=models.JSONField(default=dict),
        ),
    ]
