# Generated by Django 6.0.3 on 2026-05-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishi', '0016_useraccount_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('doorstep', 'Door-step Delivery'), ('pickup', 'Self Pickup')], default='doorstep', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online (UPI)'), ('cod', 'Cash on Delivery'), ('none', 'No Payment (Pickup)')], default='online', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cod_pending', 'Cash on Delivery Pending'), ('pickup_pending', 'Awaiting Self-Pickup'), ('paid', 'Paid'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
